name = "agx1"
main = "worker.js"
compatibility_date = "2025-12-08"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "LISTING_IMAGES"
bucket_name = "emerald-listing-images"

[[r2_buckets]]
binding = "PRIVATE_DOCS"
bucket_name = "emerald-private-docs"

[[d1_databases]]
binding = "DB"
database_name = "emerald-db"
database_id = " โ…๏ธ wrangler 4.53.0"

[images]
binding = "IMAGES"
account_id = "f8fa50087b953f3079ece442868354ec"
